In [ ]:
Question 1:

Given the following DataFrame representing student data:

import pandas as pd

data = {

'Name': ['John', 'Mary', 'Alex', 'Sarah', 'Jack'],

'Math_Score': [85, 78, 92, 95, 80],

'Science_Score': [90, 92, 88, 89, 85],

'History_Score': [88, 85, 91, 92, 86]

}

df = pd.DataFrame(data)

a) Calculate the total number of students in the DataFrame.

b) Calculate the average score for each subject (Math, Science, and History).

c) Find the student with the highest total score (sum of all three subjects).

In [2]:
import pandas as pd

data = {
    'Name': ['John', 'Mary', 'Alex', 'Sarah', 'Jack'],
    'Math_Score': [85, 78, 92, 95, 80],
    'Science_Score': [90, 92, 88, 89, 85],
    'History_Score': [88, 85, 91, 92, 86]
}

df = pd.DataFrame(data)

# a) Calculate the total number of students in the DataFrame.
total_students = len(df)
print("Total number of students:", total_students)

# b) Calculate the average score for each subject.
average_math_score = df['Math_Score'].mean()
average_science_score = df['Science_Score'].mean()
average_history_score = df['History_Score'].mean()
print("Average Math Score:", average_math_score)
print("Average Science Score:", average_science_score)
print("Average History Score:", average_history_score)

# c) Find the student with the highest total score (sum of all three subjects).
df['Total_Score'] = df['Math_Score'] + df['Science_Score'] + df['History_Score']
student_with_highest_score = df.loc[df['Total_Score'].idxmax()]
print("Student with the highest total score:")
print(student_with_highest_score)

Total number of students: 5
Average Math Score: 86.0
Average Science Score: 88.8
Average History Score: 88.4
Student with the highest total score:
Name             Sarah
Math_Score          95
Science_Score       89
History_Score       92
Total_Score        276
Name: 3, dtype: object

In [ ]:
Question 2:

Given the following DataFrame representing sales data:
data = {

'Date': ['2023-07-01', '2023-07-02', '2023-07-03', '2023-07-04', '2023-07-05'],

'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],

'Sales': [1000, 500, 800, 1200, 600],

'Profit': [200, 100, 150, 250, 120]

}

df = pd.DataFrame(data)
a) Calculate the total sales and total profit for each product.

b) Find the product with the highest total sales and highest total profit.

c) Add a new column "Profit_Percentage" that contains the percentage of profit for each sale.

In [3]:
import pandas as pd

data = {
    'Date': ['2023-07-01', '2023-07-02', '2023-07-03', '2023-07-04', '2023-07-05'],
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],
    'Sales': [1000, 500, 800, 1200, 600],
    'Profit': [200, 100, 150, 250, 120]
}

df = pd.DataFrame(data)

# a) Calculate the total sales and total profit for each product.
product_totals = df.groupby('Product').agg({'Sales': 'sum', 'Profit': 'sum'})

# b) Find the product with the highest total sales and highest total profit.
product_highest_sales = product_totals['Sales'].idxmax()
product_highest_profit = product_totals['Profit'].idxmax()

# c) Add a new column "Profit_Percentage" that contains the percentage of profit for each sale.
df['Profit_Percentage'] = (df['Profit'] / df['Sales']) * 100

print("Total sales and total profit for each product:")
print(product_totals)
print("\nProduct with the highest total sales:", product_highest_sales)
print("Product with the highest total profit:", product_highest_profit)
print("\nDataFrame with added Profit_Percentage column:")
print(df)

Total sales and total profit for each product:
         Sales  Profit
Product
Laptop    2200     450
Phone     1100     220
Tablet     800     150

Product with the highest total sales: Laptop
Product with the highest total profit: Laptop

DataFrame with added Profit_Percentage column:
         Date Product  Sales  Profit  Profit_Percentage
0  2023-07-01  Laptop   1000     200          20.000000
1  2023-07-02   Phone    500     100          20.000000
2  2023-07-03  Tablet    800     150          18.750000
3  2023-07-04  Laptop   1200     250          20.833333
4  2023-07-05   Phone    600     120          20.000000

In [ ]:
Question 3:

Given the following DataFrame representing information about employees in a company:
data = {

'Employee_ID': [1001, 1002, 1003, 1004, 1005],

'Name': ['John', 'Sarah', 'Alex', 'Emily', 'Jack'],

'Department': ['Marketing', 'Accounting', 'IT', 'HR', 'Marketing'],

'Salary': [50000, 60000, 55000, 58000, 52000]

}

df = pd.DataFrame(data)
a) Calculate the average salary for each department and display the results as a new DataFrame.

b) Find the department with the highest average salary.

c) Add a new column "Salary_Category" based on the following conditions:

High: Salary > average salary for the department.

Low: Salary <= average salary for the department.

In [4]:
import pandas as pd

data = {
    'Employee_ID': [1001, 1002, 1003, 1004, 1005],
    'Name': ['John', 'Sarah', 'Alex', 'Emily', 'Jack'],
    'Department': ['Marketing', 'Accounting', 'IT', 'HR', 'Marketing'],
    'Salary': [50000, 60000, 55000, 58000, 52000]
}

df = pd.DataFrame(data)

# a) Calculate the average salary for each department and display the results as a new DataFrame.
department_avg_salary = df.groupby('Department')['Salary'].mean().reset_index()
department_avg_salary.columns = ['Department', 'Average_Salary']

# b) Find the department with the highest average salary.
highest_avg_salary_dept = department_avg_salary['Department'].iloc[department_avg_salary['Average_Salary'].idxmax()]

# c) Add a new column "Salary_Category" based on the salary conditions.
average_salary_map = department_avg_salary.set_index('Department')['Average_Salary'].to_dict()

def categorize_salary(row):
    if row['Salary'] > average_salary_map.get(row['Department']):
        return 'High'
    else:
        return 'Low'

df['Salary_Category'] = df.apply(categorize_salary, axis=1)

print("Average salary for each department:")
print(department_avg_salary)
print("\nDepartment with the highest average salary:", highest_avg_salary_dept)
print("\nDataFrame with added Salary_Category column:")
print(df)

Average salary for each department:
   Department  Average_Salary
0  Accounting         60000.0
1          HR         58000.0
2          IT         55000.0
3   Marketing         51000.0

Department with the highest average salary: Accounting

DataFrame with added Salary_Category column:
   Employee_ID   Name  Department  Salary Salary_Category
0         1001   John   Marketing   50000             Low
1         1002  Sarah  Accounting   60000             Low
2         1003   Alex          IT   55000             Low
3         1004  Emily          HR   58000             Low
4         1005   Jack   Marketing   52000            High

In [ ]:
Question 4:

Given the following DataFrame representing sales data for different regions:
data = {

'Region': ['North', 'South', 'East', 'West', 'North', 'West'],

'Sales': [1000, 800, 1200, 900, 1100, 750],

'Profit': [200, 150, 250, 180, 220, 130]

}

df = pd.DataFrame(data)
a) Calculate the total sales and total profit for each region.
b) Find the region with the highest total sales and highest total profit.
c) Display the number of occurrences of each region in the DataFrame.

In [5]:
import pandas as pd

# Given DataFrame for sales data
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'West'],
    'Sales': [1000, 800, 1200, 900, 1100, 750],
    'Profit': [200, 150, 250, 180, 220, 130]
}

df = pd.DataFrame(data)

# a) Calculate the total sales and total profit for each region.
region_totals = df.groupby('Region').agg({'Sales': 'sum', 'Profit': 'sum'}).reset_index()

# b) Find the region with the highest total sales and highest total profit.
highest_sales_region = region_totals.loc[region_totals['Sales'].idxmax()]
highest_profit_region = region_totals.loc[region_totals['Profit'].idxmax()]

# c) Display the number of occurrences of each region in the DataFrame.
region_occurrences = df['Region'].value_counts().reset_index()
region_occurrences.columns = ['Region', 'Occurrences']

print("Total sales and profit for each region:")
print(region_totals)
print("\nRegion with the highest total sales:")
print(highest_sales_region)
print("\nRegion with the highest total profit:")
print(highest_profit_region)
print("\nNumber of occurrences of each region:")
print(region_occurrences)

Total sales and profit for each region:
  Region  Sales  Profit
0   East   1200     250
1  North   2100     420
2  South    800     150
3   West   1650     310

Region with the highest total sales:
Region    North
Sales      2100
Profit      420
Name: 1, dtype: object

Region with the highest total profit:
Region    North
Sales      2100
Profit      420
Name: 1, dtype: object

Number of occurrences of each region:
  Region  Occurrences
0  North            2
1   West            2
2  South            1
3   East            1

In [ ]:
Question 5:

Given the following DataFrame representing student scores in different subjects:
data = {

'Name': ['John', 'Mary', 'Alex', 'Sarah', 'Jack'],

'Math_Score': [85, 78, 92, 95, 80],

'Science_Score': [90, 92, 88, 89, 85],

'History_Score': [88, 85, 91, 92, 86]

}

df = pd.DataFrame(data)
a) Calculate the average score for each student.

b) Find the student with the highest average score.

c) Add a new row for a student "Ella" with scores [88, 84, 90] in Math, Science, and History, respectively.

In [10]:
import pandas as pd

# Given DataFrame for student scores
data = {
    'Name': ['John', 'Mary', 'Alex', 'Sarah', 'Jack'],
    'Math_Score': [85, 78, 92, 95, 80],
    'Science_Score': [90, 92, 88, 89, 85],
    'History_Score': [88, 85, 91, 92, 86]
}

df = pd.DataFrame(data)

# a) Calculate the average score for each student.
df['Average_Score'] = df[['Math_Score', 'Science_Score', 'History_Score']].mean(axis=1)

# b) Find the student with the highest average score.
highest_avg_student = df.loc[df['Average_Score'].idxmax()]

# c) Add a new row for a student "Ella" with scores [88, 84, 90] in Math, Science, and History, respectively.
new_student = {'Name': 'Ella', 'Math_Score': 88, 'Science_Score': 84, 'History_Score': 90, 'Average_Score': None}
new_student_df = pd.DataFrame([new_student])

df = pd.concat([df, new_student_df], ignore_index=True)

print("Average score for each student:")
print(df)

print("\nStudent with the highest average score:")
print(highest_avg_student)

Average score for each student:
    Name  Math_Score  Science_Score  History_Score Average_Score
0   John          85             90             88     87.666667
1   Mary          78             92             85          85.0
2   Alex          92             88             91     90.333333
3  Sarah          95             89             92          92.0
4   Jack          80             85             86     83.666667
5   Ella          88             84             90          None

Student with the highest average score:
Name             Sarah
Math_Score          95
Science_Score       89
History_Score       92
Average_Score     92.0
Name: 3, dtype: object

In [ ]:
Question 6:

Given the following DataFrame representing sales data for different products:
data = {

'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],

'Sales': [1000, 500, 800, 1200, 600],

'Profit': [200, 100, 150, 250, 120]

}

df = pd.DataFrame(data)
a) Calculate the total sales and total profit for each product.

b) Find the product with the highest total sales and highest total profit.

c) Calculate the profit percentage for each product (Profit / Sales * 100) and add it as a new column.

In [11]:
import pandas as pd

# Given DataFrame for sales data
data = {
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],
    'Sales': [1000, 500, 800, 1200, 600],
    'Profit': [200, 100, 150, 250, 120]
}

df = pd.DataFrame(data)

# a) Calculate the total sales and total profit for each product.
product_sales = df.groupby('Product')['Sales'].sum()
product_profit = df.groupby('Product')['Profit'].sum()

# b) Find the product with the highest total sales and highest total profit.
product_highest_sales = product_sales.idxmax()
product_highest_profit = product_profit.idxmax()

# c) Calculate the profit percentage for each product and add it as a new column.
df['Profit_Percentage'] = (df['Profit'] / df['Sales']) * 100

print("Total sales for each product:")
print(product_sales)

print("\nTotal profit for each product:")
print(product_profit)

print("\nProduct with the highest total sales:", product_highest_sales)
print("Product with the highest total profit:", product_highest_profit)

print("\nDataFrame with profit percentage:")
print(df)

Total sales for each product:
Product
Laptop    2200
Phone     1100
Tablet     800
Name: Sales, dtype: int64

Total profit for each product:
Product
Laptop    450
Phone     220
Tablet    150
Name: Profit, dtype: int64

Product with the highest total sales: Laptop
Product with the highest total profit: Laptop

DataFrame with profit percentage:
  Product  Sales  Profit  Profit_Percentage
0  Laptop   1000     200          20.000000
1   Phone    500     100          20.000000
2  Tablet    800     150          18.750000
3  Laptop   1200     250          20.833333
4   Phone    600     120          20.000000

In [ ]:
Question 7:

Given the following DataFrame representing employee data:
data = {

'Name': ['John', 'Sarah', 'Alex', 'Emily', 'Jack'],

'Age': [25, 30, 22, 27, 29],

'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],

'Salary': [50000, 60000, 55000, 58000, 52000]

}

df = pd.DataFrame(data)
a) Calculate the average age and average salary for all employees.

b) Find the employee with the highest salary and display their details.

c) Add a new employee with Name: "Ella", Age: 24, Gender: "Female", Salary: 56000.

In [14]:
import pandas as pd

# Given DataFrame for employee data
data = {
    'Name': ['John', 'Sarah', 'Alex', 'Emily', 'Jack'],
    'Age': [25, 30, 22, 27, 29],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'Salary': [50000, 60000, 55000, 58000, 52000]
}

df = pd.DataFrame(data)

# a) Calculate the average age and average salary for all employees.
average_age = df['Age'].mean()
average_salary = df['Salary'].mean()

# b) Find the employee with the highest salary and display their details.
highest_salary_employee = df[df['Salary'] == df['Salary'].max()]

# c) Add a new employee
new_employee = {'Name': 'Ella', 'Age': 24, 'Gender': 'Female', 'Salary': 56000}
new_employee_df = pd.DataFrame([new_employee])  # Create a new DataFrame with the new employee
df = pd.concat([df, new_employee_df], ignore_index=True)  # Concatenate the DataFrames

print("Average Age:", average_age)
print("Average Salary:", average_salary)

print("\nEmployee with the highest salary:")
print(highest_salary_employee)

print("\nDataFrame with the new employee:")
print(df)

Average Age: 26.6
Average Salary: 55000.0

Employee with the highest salary:
    Name  Age  Gender  Salary
1  Sarah   30  Female   60000

DataFrame with the new employee:
    Name  Age  Gender  Salary
0   John   25    Male   50000
1  Sarah   30  Female   60000
2   Alex   22    Male   55000
3  Emily   27  Female   58000
4   Jack   29    Male   52000
5   Ella   24  Female   56000

In [ ]:
Question 8:

Given the following DataFrame representing sales data for different products:
data = {

'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],

'Sales': [1000, 500, 800, 1200, 600],

'Profit': [200, 100, 150, 250, 120]

}

df = pd.DataFrame(data)
a) Calculate the total sales and total profit for each product.

b) Find the product with the highest total sales and highest total profit.

c) Add a new column "Profit_Percentage" that contains the percentage of profit for each sale.

In [15]:
import pandas as pd

# Given DataFrame for sales data
data = {
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],
    'Sales': [1000, 500, 800, 1200, 600],
    'Profit': [200, 100, 150, 250, 120]
}

df = pd.DataFrame(data)

# a) Calculate the total sales and total profit for each product.
product_totals = df.groupby('Product').agg({'Sales': 'sum', 'Profit': 'sum'})

# b) Find the product with the highest total sales and highest total profit.
product_highest_sales = product_totals['Sales'].idxmax()
product_highest_profit = product_totals['Profit'].idxmax()

# c) Add a new column "Profit_Percentage"
df['Profit_Percentage'] = (df['Profit'] / df['Sales']) * 100

print("Total Sales and Profit for Each Product:")
print(product_totals)

print("\nProduct with the Highest Total Sales:", product_highest_sales)
print("Product with the Highest Total Profit:", product_highest_profit)

print("\nDataFrame with Profit Percentage:")
print(df)

Total Sales and Profit for Each Product:
         Sales  Profit
Product
Laptop    2200     450
Phone     1100     220
Tablet     800     150

Product with the Highest Total Sales: Laptop
Product with the Highest Total Profit: Laptop

DataFrame with Profit Percentage:
  Product  Sales  Profit  Profit_Percentage
0  Laptop   1000     200          20.000000
1   Phone    500     100          20.000000
2  Tablet    800     150          18.750000
3  Laptop   1200     250          20.833333
4   Phone    600     120          20.000000

In [ ]:
Question 9:

Given the following DataFrame representing sales data for different regions:
data = {

'Region': ['North', 'South', 'East', 'West', 'North', 'West'],

'Sales': [1000, 800, 1200, 900, 1100, 750],

'Profit': [200, 150, 250, 180, 220, 130]

}

df = pd.DataFrame(data)
a) Calculate the total sales and total profit for each region.

b) Find the region with the highest total sales and highest total profit.

c) Display the number of occurrences of each region in the DataFrame.

In [16]:
import pandas as pd

# Given DataFrame for sales data in different regions
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'West'],
    'Sales': [1000, 800, 1200, 900, 1100, 750],
    'Profit': [200, 150, 250, 180, 220, 130]
}

df = pd.DataFrame(data)

# a) Calculate the total sales and total profit for each region.
region_totals = df.groupby('Region').agg({'Sales': 'sum', 'Profit': 'sum'})

# b) Find the region with the highest total sales and highest total profit.
region_highest_sales = region_totals['Sales'].idxmax()
region_highest_profit = region_totals['Profit'].idxmax()

# c) Display the number of occurrences of each region in the DataFrame.
region_occurrences = df['Region'].value_counts()

print("Total Sales and Profit for Each Region:")
print(region_totals)

print("\nRegion with the Highest Total Sales:", region_highest_sales)
print("Region with the Highest Total Profit:", region_highest_profit)

print("\nNumber of Occurrences of Each Region:")
print(region_occurrences)

Total Sales and Profit for Each Region:
        Sales  Profit
Region
East     1200     250
North    2100     420
South     800     150
West     1650     310

Region with the Highest Total Sales: North
Region with the Highest Total Profit: North

Number of Occurrences of Each Region:
Region
North    2
West     2
South    1
East     1
Name: count, dtype: int64

In [ ]:
Question 10:

Given the following DataFrame representing student data:
data = {

'Name': ['John', 'Mary', 'Alex', 'Sarah', 'Jack'],

'Math_Score': [85, 78, 92, 95, 80],

'Science_Score': [90, 92, 88, 89, 85],

'History_Score': [88, 85, 91, 92, 86]

}

df = pd.DataFrame(data)
a) Calculate the overall average score for each student and add it as a new column "Average_Score."

b) Find the student with the highest average score and display their details.

c) Add a new row for a student "Ella" with scores [88, 84, 90] in Math, Science, and History, respectively.

In [3]:
import pandas as pd

# Given DataFrame for student data
data = {
    'Name': ['John', 'Mary', 'Alex', 'Sarah', 'Jack'],
    'Math_Score': [85, 78, 92, 95, 80],
    'Science_Score': [90, 92, 88, 89, 85],
    'History_Score': [88, 85, 91, 92, 86]
}

df = pd.DataFrame(data)

# a) Calculate the overall average score for each student and add it as a new column "Average_Score."
df['Average_Score'] = df[['Math_Score', 'Science_Score', 'History_Score']].mean(axis=1)

# b) Find the student with the highest average score and display their details.
highest_avg_student = df.loc[df['Average_Score'].idxmax()]

# c) Add a new row for a student "Ella" with scores [88, 84, 90] in Math, Science, and History, respectively.
new_student = pd.DataFrame({'Name': ['Ella'], 'Math_Score': [88], 'Science_Score': [84], 'History_Score': [90]})
df = pd.concat([df, new_student], ignore_index=True)
df['Average_Score'] = df[['Math_Score', 'Science_Score', 'History_Score']].mean(axis=1)

print("Overall Average Score for Each Student:")
print(df)

print("\nStudent with the Highest Average Score:")
print(highest_avg_student)

Overall Average Score for Each Student:
    Name  Math_Score  Science_Score  History_Score  Average_Score
0   John          85             90             88      87.666667
1   Mary          78             92             85      85.000000
2   Alex          92             88             91      90.333333
3  Sarah          95             89             92      92.000000
4   Jack          80             85             86      83.666667
5   Ella          88             84             90      87.333333

Student with the Highest Average Score:
Name             Sarah
Math_Score          95
Science_Score       89
History_Score       92
Average_Score     92.0
Name: 3, dtype: object